### Word Embedding Techniques using Embedding Layer in Keras

In [7]:
### Libraries USed Tensorflow> 2.0  and keras

In [8]:
!pip install tensorflow-gpu

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [9]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [10]:
##tensorflow >2.0
# Apply One Hot Encoding
from tensorflow.keras.preprocessing.text import one_hot

In [11]:
### corpus
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [12]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [13]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [14]:
# Print indexes with 1 in the vector of each document
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[285, 170, 492, 118], [285, 170, 492, 101], [285, 52, 492, 215], [132, 50, 170, 489, 28], [132, 50, 170, 489, 265], [287, 285, 96, 492, 440], [33, 154, 215, 489]]


### Word Embedding Representation

In [15]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [16]:
import numpy as np

Apply Padding Techniques to fix the length of each document

In [17]:
## pre padding
sent_length=8  # Fix max length to 8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 285 170 492 118]
 [  0   0   0   0 285 170 492 101]
 [  0   0   0   0 285  52 492 215]
 [  0   0   0 132  50 170 489  28]
 [  0   0   0 132  50 170 489 265]
 [  0   0   0 287 285  96 492 440]
 [  0   0   0   0  33 154 215 489]]


In [18]:
## post padding
sent_length=8  # Fix max length to 8
embedded_docs1=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs1)

[[285 170 492 118   0   0   0   0]
 [285 170 492 101   0   0   0   0]
 [285  52 492 215   0   0   0   0]
 [132  50 170 489  28   0   0   0]
 [132  50 170 489 265   0   0   0]
 [287 285  96 492 440   0   0   0]
 [ 33 154 215 489   0   0   0   0]]


In [19]:
## 10 feature dimesnions (convert each word/value to vector representation)
dim=10

In [21]:
#  CREATE MODEL
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length)) # Embedding layer - (vocab_size,no_of_features,total_sentence_length)
model.compile('adam','mse')  # adam optimizer, mean squared error

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [22]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [23]:
## First Sentence - 'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 285, 170, 492, 118], dtype=int32)

In [ ]:
# each point in above document is represented as a vector
model.predict(embedded_docs[0])

In [24]:
import tensorflow as tf
# Vector representation of all documents
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 858ms/step
[[[ 2.14411058e-02  3.87722887e-02  3.60320918e-02  3.68526466e-02
    1.06173158e-02 -4.92646545e-03  4.80604209e-02 -1.26862526e-03
    3.15293558e-02 -1.80644393e-02]
  [ 2.14411058e-02  3.87722887e-02  3.60320918e-02  3.68526466e-02
    1.06173158e-02 -4.92646545e-03  4.80604209e-02 -1.26862526e-03
    3.15293558e-02 -1.80644393e-02]
  [ 2.14411058e-02  3.87722887e-02  3.60320918e-02  3.68526466e-02
    1.06173158e-02 -4.92646545e-03  4.80604209e-02 -1.26862526e-03
    3.15293558e-02 -1.80644393e-02]
  [ 2.14411058e-02  3.87722887e-02  3.60320918e-02  3.68526466e-02
    1.06173158e-02 -4.92646545e-03  4.80604209e-02 -1.26862526e-03
    3.15293558e-02 -1.80644393e-02]
  [ 3.86434235e-02 -2.99665816e-02  1.98868252e-02  7.12523609e-03
    1.82290189e-02  2.89757736e-02  1.26912110e-02 -3.36765125e-03
    1.94745548e-02 -4.23048250e-02]
  [-2.10771691e-02 -9.51891020e-03  2.98273563e-03  3.23741473e-02
   -6.16120175e-03  8.89422745e-03  4.530712

In [25]:
embedded_docs[0]

array([  0,   0,   0,   0, 285, 170, 492, 118], dtype=int32)

In [26]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
[[ 0.02144111  0.03877229  0.03603209  0.03685265  0.01061732 -0.00492647
   0.04806042 -0.00126863  0.03152936 -0.01806444]
 [ 0.02144111  0.03877229  0.03603209  0.03685265  0.01061732 -0.00492647
   0.04806042 -0.00126863  0.03152936 -0.01806444]
 [ 0.02144111  0.03877229  0.03603209  0.03685265  0.01061732 -0.00492647
   0.04806042 -0.00126863  0.03152936 -0.01806444]
 [ 0.02144111  0.03877229  0.03603209  0.03685265  0.01061732 -0.00492647
   0.04806042 -0.00126863  0.03152936 -0.01806444]
 [ 0.03864342 -0.02996658  0.01988683  0.00712524  0.01822902  0.02897577
   0.01269121 -0.00336765  0.01947455 -0.04230483]
 [-0.02107717 -0.00951891  0.00298274  0.03237415 -0.0061612   0.00889423
   0.04530713  0.01970149  0.02691741  0.02858956]
 [ 0.00388693 -0.02894082 -0.04188225 -0.02307769  0.03015821 -0.01007421
  -0.02578553  0.01233435 -0.00607795 -0.02590321]
 [-0.02662017  0.0157318  -0.04474114 -0.01243926 -0.03927076  0.00865165
  -0.04693334